### ISSUE TITLE
libtorrent for storage

### ISSUE THREAD

**Issue by ryscheng** [oasisprotocol/oasis-core#130]
One option for storage, is to just run libtorrent over compute nodes.
If compute nodes are caching their view of the state anyway, we can just have them replicate the values they need amongst themselves.
Optionally, we could also use a separate committee.

We can still let old values expire, the only strict requirement is that current data is replicated at least f times.

**Comment by Yawning** [comment]
We have a workable storage system now so I don't think this will ever happen.
