### ISSUE TITLE
storage/client: Use a more clever approach to choose the order in which to read from connected nodes

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#1815]
After #1792 is merged, the storage client will try to read from the connected nodes in random order:

```
... trimmed ...

rng := rand.New(mathrand.New(cryptorand.Reader))

var err error
var resp interface{}
for _, randIndex := range rng.Perm(n) {
	clientState := b.connectedNodesState.clientStates[randIndex]
	resp, err = fn(ctx, clientState.client)

.. trimmed ...
```

Consider using a more clever approach to select the order in which to read from the connected storage nodes.

One possible way would be to track per-node statistics and have a policy to prioritize based on that. This should be done in a manner that is reusable across many different protocols, e.g., instead of just storage gRPC requests it should also be informed by messages received via P2P etc. So a common "peer reputation tracking" mechanism.

**Comment by kostko** [comment]
Obsoleted by #4459 which does peer scoring.
