### ISSUE TITLE
Slash stake for malicious txn schedulers

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-core#1931]
In `go/roothash/api/commitment/pool.go` when we discover that a txn sched has signed two different batches for the same committee, we should slash its stake.  Currently, only a warning is printed.

One possible design is to introduce a `Slasher` interface which is passed to the methods that need to decide whether to slash and then call into that interface when slashable offences occur.

## Acceptance Criteria
* Stake is slashed for malicious txn schedulers.

**Comment by kostko** [comment]
Superseded by #3685.
