### ISSUE TITLE
Transfer between staking and runtime ledgers

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#2077]
As the staking ledger should be used exclusively for staking, we need to support transfer of tokens between the staking ledger (whcih lives in the BFT committee) and the ledger(s) maintained by the runtime(s). The runtime ledgers have runtime-specific semantics.

The transfer operation(s) would consist of two parts:
* Update of the staking ledger (can only be done by the BFT committee, e.g., the roothash ABCI application), which happens by updating the ABCI application state.
* Update of the runtime ledger (can only be done by the runtime as the ledger has runtime-specific semantics), which happens by updating storage.

Care must be taken to avoid any possibility of losing or duplicating funds (e.g., the operation(s) must be atomic).

Notes:
* The runtime probably needs some way to query staking balances. Care must be taken as the staking accounts can change while the runtime is executing.
* The runtime needs to signal the requested change in the staking account(s) to the BFT committee. Related to the first note, while the BFT committee can (and should) verify that there is enough balance in the staking account, the only thing it can do to prevent breaking atomicity is to abort the whole round (and thus many unrelated batches) as it has no way of reverting only specific updates to storage. Care must be taken to not turn this into a DoS vector.
* Perhaps there is a way to make these transfers multi-phase where the staking account is first locked and then transfers are performed knowing that the balance cannot change while the runtime is executing transactions. Again care must be taken to not turn any such locking scheme into a DoS vector.
* To prevent spamming only owners of staking accounts should be able to initiate such transfers. This means that the runtime needs to provide a valid authorization signature for the given staking account to the BFT committee (this signature would be provided by stakeholder, e.g., embedded in a regular transaction).

Probably out of scope:
* ~~With this feature in place, a badly written runtime can cause funds to appear from thin air and transfer them to the staking ledger which can potentially compromise the rest of the system. This probably cannot be avoided.~~ (see #2302)

**Comment by kostko** [comment]
> With this feature in place, a badly written runtime can cause funds to appear from thin air

Thinking about it, each runtime should probably have an account in the consensus layer which would be checked and updated during these operations. That would ensure that it can't create extra tokens as tokens would need to be transferred to the runtime before they can be transferred out.

**Comment by pro-wh** [comment]
^ I'll move this to a new subissue, so that we can more easily consider it for an earlier phase, independently from the runtime-related work

**Comment by kostko** [comment]
Now specified in [ADR 0003](docs/adr/0003-consensus-runtime-token-transfer.md).
