### ISSUE TITLE
Add IsReady/WaitReady to client protocol

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#2130]
We should add `IsReady` and `WaitReady` RPC methods to the client protocol that could be used to check whether the node has finished initializing and is ready to process requests.

Currently there already exist `IsSynced` and `WaitSync` which check for consensus sync, but these new methods would be useful for the worker nodes to additionally check that the hosted runtimes have also started successfully.

A node would be ready iff everything of the following is true:
* Consensus has finished syncing.
* All configured runtimes are registered.
* All configured workers have finished initializing.
* All hosted runtime processes are ready to process requests.

There should also be a corresponding `debug client wait-ready` command.

**Comment by ptrus** [comment]
Just posting two more code references that can be done with this issue:

https://github.com/oasislabs/oasis-core/blob/3d5e7dc02d5150fe0d5dcb54aa773984bf0a3872/go/oasis-test-runner/scenario/e2e/runtime.go#L556-L559

https://github.com/oasislabs/oasis-core/blob/3d5e7dc02d5150fe0d5dcb54aa773984bf0a3872/go/worker/keymanager/worker.go#L186-L189
