### ISSUE TITLE
staking: track tokens transferred to runtime in a per-runtime balance

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core#2302]
> With this feature in place, a badly written runtime can cause funds to appear from thin air

Thinking about it, each runtime should probably have an account in the consensus layer which would be checked and updated during these operations. That would ensure that it can't create extra tokens as tokens would need to be transferred to the runtime before they can be transferred out.

_Originally posted by @kostko in https://github.com/oasislabs/oasis-core/issues/2077#issuecomment-544914873_

**Comment by kostko** [comment]
Superseded by #3429.
