### ISSUE TITLE
Optimize size of compute and merge commits

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#2304]
We should look into possible ways to optimize the size of compute and merge commits, under the assumption that in the optimal case (no discrepancies) all the commits will be the same.

For example, since merge nodes aggregate all compute commits and only do merge commits in case there is no discrepancy, they can include just compute commit signatures (as they are all signing the same thing).

*Estimated cost: <1 sprint*

**Comment by Yawning** [comment]
> they can include just compute commit signatures (as they are all signing the same thing)

They are?  A compute commit includes the RAK signature and Storage Signatures.

The former is expected to be different (and it not being different is a catastrophic failure).  The latter may be the same in the common case (assuming the slice is sorted), but is not guaranteed to be.

**Comment by kostko** [comment]
So at least some parts should be the same (per-`CommitteeID` once there are multiple parallel committees):
* `ComputeResultsHeader` (subject to DD so it must be identical).
* `TxnSchedSig`, `InputRoot` and `InputStorageSigs` (received by all nodes from the transaction scheduler which should match unless the txn scheduler is double-signing).

So basically everything except `StorageSignatures` (could be in different order and to different nodes) and `RakSig` (different enclaves).

We can still compress the other fields and reconstruct them when verifying the signatures, but the tradeoff is complexity so maybe it is better not to do this for now?

**Comment by Yawning** [comment]
> complexity so maybe it is better not to do this for now?

At this point in time, I'm leaning towards avoiding adding additional complexity to code that runs at the consensus layer.
