### ISSUE TITLE
Add debug consensus halt override

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#2327]
https://github.com/oasislabs/oasis-core/pull/2309 adds a "halt epoch" consensus parameter.

While there is not yet implemented on-chain support for updating consensus parameters there should be a debug way to override the halt epoch on the node locally to support "off-chain" scheduling of the network halt.

Alternatively, implement on chain voting and support for updating the halt epoch parameter.

**Comment by kostko** [comment]
The same can be achieved now via upgrade descriptors.
