### ISSUE TITLE
go/worker/txnscheduler: CheckTx should use a queue

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-core#2548]
PR #2502 implemented optional checking of transactions before queuing them in the transaction scheduler.  However, the way it's currently implemented, each check is done serially, which can slow-down execution if checking is enabled.

This should be optimized by using a separate queue for CheckTx requests and batching them, as suggested in https://github.com/oasislabs/oasis-core/pull/2502#discussion_r365741640.

**Comment by samohyes** [comment]
So basiclly, right now, the txs are checked before added in txnscheduler. The checks including like whether there is enough balance in the accout or whether it's a successful contract call, right? The code looks complicated now.

**Comment by abukosek** [comment]
The checks are disabled by default for now, so the behavior is the same as before.  If enabled, the checks depend on the runtime that's used.  In our oasis-runtime, the checks are done here: https://github.com/oasislabs/oasis-runtime/blob/9bc96c04d1e6503096aaefdfa6b999b26b972943/src/methods.rs#L26-L45

**Comment by samohyes** [comment]
Thanks for the reply. 
As I can see the core check here in the CheckTx function is here 
https://github.com/oasislabs/oasis-core/blob/master/go/worker/txnscheduler/committee/node.go#L164
with the call 
`resp, err := workerHost.Call(ctx, checkRq)`

So according to what you said, this workerHost.Call will call the check in oasis-runtime(the link you provides), right?

**Comment by abukosek** [comment]
Yes, the `workerHost.Call()` will make a call into the SGX enclave that's running the runtime and the method I linked before will be executed.  The rest of the new code is basically just error checking and serialization/deserialization.
