### ISSUE TITLE
Display Genesis document's hash when creating transactions with the CLI

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#2871]
##### SUMMARY

When a user creates a transaction with the CLI, e.g.:
```
oasis-node stake account gen_transfer \
  --genesis.file /localhostdir/genesis.json \
  --signer ledger \
  --signer.ledger.address oasis19hpt4y2reqwyfqcd53asjchdqf468chr673y6jn07xjp36w32jlscf0me \
  --signer.ledger.index 1 \
  --signer.dir /localhostdir/entity/
  --stake.amount 170000000000 \
  --stake.transfer.destination A1X90rT/WK4AOTh/dJsUlOqNDV/nXM6ZU+h+blS9pto= \
  --transaction.file tx_transfer.json \
  --transaction.nonce 1 \
  --transaction.fee.gas 1000 \
  --transaction.fee.amount 2000
```

and uses a Ledger device to sign it, he needs to verify the Genesis document's hash on the Ledger device's screen.

To make that verification easier, print the Genesis document's hash to the log when creating a transaction with one of the `oasis-node stake account get_*` commands.

##### ISSUE TYPE
- Feature Idea

**Comment by kostko** [comment]
Also `show_tx` should probably display the genesis document hash as well.

**Comment by kostko** [comment]
It would also be cool to have a genesis subcommand for deriving and displaying the genesis document hash (maybe this could be part of `oasis-node genesis check`).

**Comment by tjanez** [comment]
> It would also be cool to have a genesis subcommand for deriving and displaying the genesis document hash (maybe this could be part of `oasis-node genesis check`).

This part has been extracted to #3136.
