### ISSUE TITLE
Remove `gorilla/websocket` replace directive once it's not needed

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#2931]
Remove the `gorilla/websocket` replace directive once it's not needed anymore.

* [ ] Once `spf13/cobra` version with bumped dependencies is released (https://github.com/spf13/cobra/issues/1091) we can replace the directive with a `spf13/cobra` replace. 

* [ ] Once `tendermint` doesn't depend on a version of `spf13/cobra`  with `gorilla/websocket@1.4.0`, the replace directive can be removed. At this point also remove the ignored vulnerability in `.nancy-ignore`.

**Comment by Yawning** [comment]
The replace directive is long gone, and go.sum no longer references `gorilla/websocket@1.4.0`
