### ISSUE TITLE
Add oasis-node metrics that are useful for validator monitoring

### ISSUE THREAD

**Issue by Karmastic** [oasisprotocol/oasis-core#2933]
##### SUMMARY
Oasis-node exposes metrics but also has verbose logging; some logged data would be helpful if added to metrics

##### ISSUE TYPE
- Feature request

##### COMPONENT NAME

go/oasis-node/cmd/common/metrics/metrics.go
go/worker/registration
tendermint/consensus

##### ADDITIONAL INFORMATION

For our validator monitoring, we added an mtail processor with the following configuration:

```    gauge oasis_last_block_voted by network, resource_id
    gauge oasis_last_block_voted_timestamp by network, resource_id
    gauge oasis_last_block_proposed by network, resource_id
    gauge oasis_last_block_proposed_timestamp by network, resource_id
    gauge oasis_last_register_success_timestamp by network, resource_id
    gauge oasis_last_register_failure_timestamp by network, resource_id
    /Signed and pushed vote/ {
      /height=(\d+)/ {
        oasis_last_block_voted["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = $1
        oasis_last_block_voted_timestamp["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = timestamp()
      }
    }
    /enterPropose: Our turn to propose/ {
      /height=(\d+)/ {
        oasis_last_block_proposed["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = $1
        oasis_last_block_proposed_timestamp["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = timestamp()
      }
    }
    /worker\/registration/ {
      /node registered with the registry/ {
        oasis_last_register_success_timestamp["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = timestamp()
      }
    }
    /worker\/registration/ {
      /failed to register node/ {
        oasis_last_register_failure_timestamp["{{ .Values.oasis.networkId }}"]["{{ template "oasis.fullname" . }}"] = timestamp()
      }
    }
```

**Comment by kostko** [comment]
We recently added some more metrics around proposing blocks etc. (in master, will be in 20.7) and also added an up to date document describing all the supported metrics. I think your cases should be covered here, but please take a look and make sure if we've missed anything:
* https://github.com/oasislabs/oasis-core/blob/master/docs/oasis-node/metrics.md

Specifically the following two:
* `oasis_consensus_proposed_blocks`
* `oasis_consensus_signed_blocks`

**Comment by kostko** [comment]
Closing as done, if any metrics are still missing feel free to re-open the issue.

**Comment by Karmastic** [comment]
Awesome thanks for adding and documenting.
