### ISSUE TITLE
Registry query for nodes by consensus address

### ISSUE THREAD

**Issue by wjdfx** [oasisprotocol/oasis-core#2961]
In use of gRPC. In order to better process block data, methodGetBlock should include some info related to the proposer entity address or proposer nodes address.

Now I use this  method
methodGetBlock = serviceName.NewMethod("GetBlock", int64(0))
got the result :
```
{
 "version": {
    "block": 10,
    "app": 1638400
 },
 "chain_id": "41e79e2847b9188e6bf0246dc86a01a01cf11bbed6ca666b45",
 "height": 274755,
 "time": 1590845914,
 "last_block_id": {
    "hash": "Oylj7JUe36vHGbwvY9HFI0U1iZQj1VyNg/S7dnMkyQA=",
    "parts": {
       "hash": "yFZus9sNLqBq+14438QRZx1WuiKJc7Ug8pYphX0SGP4=",
       "total": 1
    }
 },
 "last_commit_hash": "0+MePs++luveOL9QG8j9ZLCR710YZ7GmFZ6QGvsJBf4=",
 "data_hash": null,
 "validators_hash": "U1+J1ANtw0wM61+xdMltO4ghx3w14H9JHGxZ9OSiFPg=",
 "next_validators_hash": "U1+J1ANtw0wM61+xdMltO4ghx3w14H9JHGxZ9OSiFPg=",
 "consensus_hash": "BICRvH3cKD93v7+R1zxE2ljD34qcvIZ0Bdi389qtoi8=",
 "app_hash": "VHEOn10lDB6HZ7rXOv8WAU3QzS0t7Hr6dZljhc5hHJU=",
 "last_results_hash": null,
 "evidence_hash": null,
 "proposer_address": "hOwR6glpRGOpwtaO4x6CAfgDyAg="
}
```

From the rusult, we can see  block proposer only has node's consensus public key: is "hOwR6glpRGOpwtaO4x6CAfgDyAg=", No entity address information, no node address information. There is no way to related them.

**Comment by kostko** [comment]
The proposer address corresponds to (in case of the Tendermint consensus backend) a Tendermint address computed from the node's consensus key. This information is available in `.Consensus.ID` in the node descriptor.

So all the information is already there you only need an index from consensus addresses to node IDs. Such an index exists internally, but is currently not exposed and it may be a good idea to expose a way to query this information.

**Comment by SmartStake** [comment]
it would be very good to have a way to know which entity proposed each block. appreciate having an api that allows me to query all blocks and determine the entity. will help flag issues with given entities
