### ISSUE TITLE
Skip some E2E tests when testing SGX runtimes

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3034]
Some of the E2E tests have nothing to do with runtimes but are still also executed in SGX. We should change this so that such tests are not executed (e.g., maybe by introducing some kind of tags for tests).

**Comment by kostko** [comment]
If we do #3043 we can just run all `e2e/runtime/*` tests and skip everything else?

**Comment by tjanez** [comment]
> If we do #3043 we can just run all `e2e/runtime/*` tests and skip everything else?

Yes, I think so.
