### ISSUE TITLE
Display stake amount in token units in CLI command output

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#3037]
##### SUMMARY

To have a better UX when using the `oasis-node` CLI with a hardware wallet (e.g. Ledger) or on its own, it should also support displaying stake amounts in token unit (rather than base units used internally).

For example, `oasis stake info` currently displays something like:
```
Total supply: 10000000000000000000
Common pool: 7999217230119682890
Last block fees: 0
Staking threshold (entity): 100000000000
Staking threshold (node-validator): 100000000000
Staking threshold (node-compute): 100000000000
Staking threshold (node-storage): 100000000000
Staking threshold (node-keymanager): 100000000000
Staking threshold (runtime-compute): 100000000000
Staking threshold (runtime-keymanager): 100000000000
```

It could display something like:
```
Total supply: AMBER 10000000000
Common pool: AMBER 7999217230.11968289
Last block fees: 0
Staking threshold (entity): AMBER 100
Staking threshold (node-validator): AMBER 100
Staking threshold (node-compute): AMBER 100
Staking threshold (node-storage): AMBER 100
Staking threshold (node-keymanager): AMBER 100
Staking threshold (runtime-compute): AMBER 100
Staking threshold (runtime-keymanager): AMBER 100
```

where `AMBER` is the token's ticker symbol for the currently running [Oasis Amber Network](https://docs.oasis.dev/operators/amber-network.html).

We could support configuring both:
- amount of *base token* units one token unit is worth (e.g. 1000000000),
- token's ticker symbol (e.g. `AMBER`).

##### ISSUE TYPE
- Feature Idea

**Comment by kostko** [comment]
It would probably be best if these attributes were configured in the genesis document as that ensures that changing any of them would generate a different chain domain separation context and thus any transactions signed using the wrong genesis document would not be valid in the original network.
