### ISSUE TITLE
Transaction status via RPC 

### ISSUE THREAD

**Issue by Messer4** [oasisprotocol/oasis-core#3047]
##### SUMMARY

When extracting data from the chain GetTransactions RPC doesnt return Tx status and some data aggregations based on failed txs can be false.
It would be awesome to have Tx Status included in Tx struct.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

GetTransactions RPC method

**Comment by kostko** [comment]
Thanks for the feature suggestion, it seems like a generally useful thing to introduce something like a `GetTransactionResults` that takes a height and returns execution results for all transactions in a given height. Alternatively we could also have something like `GetTransactionsWithResults` to reduce the number of round trips required.

**Comment by Messer4** [comment]
Second one could be more useful because reduce number of requests by RPC and increase speed of data processing
