### ISSUE TITLE
oasis-node log show error

### ISSUE THREAD

**Issue by wjdfx** [oasisprotocol/oasis-core#3112]
##### SUMMARY
oasis log show error, but the node is up and running and can be signed
```
goroutine 472033114 [sleep]:
time.Sleep(0x77359400)
	runtime/time.go:188 +0xba
github.com/tendermint/tendermint/consensus.(*Reactor).queryMaj23Routine(0xc009ae9180, 0x1d54ea0, 0xc00c38d2c0, 0xc045755040)
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:820 +0x107
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:186 +0x14b
^C
root@hz-oasis-bitcat:/mnt/vol# tail -100f oasis.log
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc04c1d1500, 0xc05a92f000, 0x414, 0x800, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc04c1d1500, 0xc05a92f000, 0x414, 0x800, 0x0, 0xc00017c738, 0xc01ae23100)
	net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc06157ebd8, 0xc05a92f000, 0x414, 0x800, 0x0, 0x0, 0x0)
	net/net.go:184 +0x8e
io.ReadAtLeast(0x1cff840, 0xc06157ebd8, 0xc05a92f000, 0x414, 0x800, 0x414, 0x1, 0x1, 0xc000fe6380)
	io/io.go:310 +0x87
io.ReadFull(...)
	io/io.go:329
github.com/tendermint/tendermint/p2p/conn.(*SecretConnection).Read(0xc04c2e1c80, 0xc04c480800, 0x400, 0x400, 0x0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/secret_connection.go:238 +0x275
bufio.(*Reader).Read(0xc05f423f20, 0xc047ef6460, 0x1, 0xa, 0xed6a29919, 0xc02cb6fe60, 0x41c876)
	bufio/bufio.go:226 +0x24f
github.com/tendermint/go-amino.(*Codec).UnmarshalBinaryLengthPrefixedReader(0xc00003e1c0, 0x1cfc4a0, 0xc05f423f20, 0x15fe4c0, 0xc0301da500, 0x417, 0x17e, 0x2710, 0x0)
	github.com/tendermint/go-amino@v0.15.0/amino.go:268 +0xfe
github.com/tendermint/tendermint/p2p/conn.(*MConnection).recvRoutine(0xc066eb51e0)
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/connection.go:579 +0x101
created by github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStart
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/connection.go:231 +0x1d9

goroutine 418108698 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:188 +0xba
github.com/tendermint/tendermint/consensus.(*Reactor).gossipVotesRoutine(0xc009ae9180, 0x1d54ea0, 0xc04c4b1bc0, 0xc04bfb7ba0)
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:672 +0x1f0
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:185 +0x10b

goroutine 417822371 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:188 +0xba
github.com/tendermint/tendermint/consensus.(*Reactor).gossipDataRoutine(0xc009ae9180, 0x1d54ea0, 0xc02a312e40, 0xc029fcda00)
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:558 +0x221
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:184 +0xcb

goroutine 628985514 [runnable]:
github.com/dgraph-io/badger/v2/table.(*Builder).handleBlock(0xc0213bcd80)
	github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:131 +0xaa
created by github.com/dgraph-io/badger/v2/table.NewTableBuilder
	github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:116 +0x205

goroutine 601744461 [sleep]:
time.Sleep(0x5f5e100)
	runtime/time.go:188 +0xba
github.com/tendermint/tendermint/consensus.(*Reactor).gossipDataRoutine(0xc009ae9180, 0x1d54ea0, 0xc018f90300, 0xc039f94c30)
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:558 +0x221
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:184 +0xcb

goroutine 608961883 [select]:
github.com/tendermint/tendermint/p2p.(*peer).metricsReporter(0xc04c7f0600)
	github.com/tendermint/tendermint@v0.33.6/p2p/peer.go:347 +0x223
created by github.com/tendermint/tendermint/p2p.(*peer).OnStart
	github.com/tendermint/tendermint@v0.33.6/p2p/peer.go:184 +0x76

goroutine 472581003 [IO wait]:
internal/poll.runtime_pollWait(0x7fd831c691f8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc01133b798, 0x72, 0x400, 0x800, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc01133b780, 0xc03261a800, 0x414, 0x800, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc01133b780, 0xc03261a800, 0x414, 0x800, 0x0, 0xc00017c738, 0xc01ae23100)
	net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc05e4ba960, 0xc03261a800, 0x414, 0x800, 0x0, 0x0, 0x0)
	net/net.go:184 +0x8e
io.ReadAtLeast(0x1cff840, 0xc05e4ba960, 0xc03261a800, 0x414, 0x800, 0x414, 0x1, 0x1, 0xc000fe6380)
	io/io.go:310 +0x87
io.ReadFull(...)
	io/io.go:329
github.com/tendermint/tendermint/p2p/conn.(*SecretConnection).Read(0xc0113dde00, 0xc01149cc00, 0x400, 0x400, 0x0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/secret_connection.go:238 +0x275
bufio.(*Reader).Read(0xc01e31c4e0, 0xc01c726370, 0x1, 0xa, 0xed6a29919, 0xc0299f1e60, 0x41c876)
	bufio/bufio.go:226 +0x24f
github.com/tendermint/go-amino.(*Codec).UnmarshalBinaryLengthPrefixedReader(0xc00003e1c0, 0x1cfc4a0, 0xc01e31c4e0, 0x15fe4c0, 0xc02a3796d0, 0x417, 0x17e, 0x2710, 0x0)
	github.com/tendermint/go-amino@v0.15.0/amino.go:268 +0xfe
github.com/tendermint/tendermint/p2p/conn.(*MConnection).recvRoutine(0xc06847b8c0)
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/connection.go:579 +0x101
created by github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStart
	github.com/tendermint/tendermint@v0.33.6/p2p/conn/connection.go:231 +0x1d9

goroutine 601744459 [select]:
github.com/tendermint/tendermint/p2p.(*peer).metricsReporter(0xc018f90300)
	github.com/tendermint/tendermint@v0.33.6/p2p/peer.go:347 +0x223
created by github.com/tendermint/tendermint/p2p.(*peer).OnStart
	github.com/tendermint/tendermint@v0.33.6/p2p/peer.go:184 +0x76

goroutine 472033114 [sleep]:
time.Sleep(0x77359400)
	runtime/time.go:188 +0xba
github.com/tendermint/tendermint/consensus.(*Reactor).queryMaj23Routine(0xc009ae9180, 0x1d54ea0, 0xc00c38d2c0, 0xc045755040)
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:820 +0x107
created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
	github.com/tendermint/tendermint@v0.33.6/consensus/reactor.go:186 +0x14b
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

oasis-node
##### OASIS NODE VERSION

```paste below
Software version: 20.8.2
Runtime protocol version: 0.14.0
Consensus protocol version: 0.25.0
Committee protocol version: 0.9.0
Tendermint core version: 0.33.6
ABCI library version: 0.16.2
Go toolchain version: 1.14.4
```

##### OS / ENVIRONMENT

Ubuntu 18.04

**Comment by kostko** [comment]
Unfortunately this doesn't show the actual error, can you include some more lines from your log?

**Comment by wjdfx** [comment]
I have deleted the log, this is the second time I have encountered this problem, I will completion next time.

**Comment by wjdfx** [comment]
`{"caller":"state.go:1788","level":"info","module":"tendermint:consensus","msg":"Added to lastPrecommits: VoteSet{H:412446 R:0 T:2 +2/3:AA28A527E07A628A640DCADA87236FB2550EC8E3EA1DB96DCC3F803DB732A02D:1:AF{"caller":"state.go:1788","level":"info","module":"tendermint:consensus","msg":"Added to lastPrecommits: VoteSet{H:412446 R:0 T:2 +2/3:AA28A527E07A628A640DCADA87236FB2550EC8E3EA1DB96DCC3F803DB732A02D:1:AFEB33B99902(0.9376142746437831) BA{70:x_xxxxx_xxxxxxxxx_xxxxxx_x_x_xx_x_xxxxxxxxx_xxxxxxxxxxxxx_xxxxxx__xxxx} map[]}","ts":"2020-07-16T18:53:10.45554886Z"}
{"caller":"state.go:1788","level":"info","module":"tendermint:consensus","msg":"Added to lastPrecommits: VoteSet{H:412446 R:0 T:2 +2/3:AA28A527E07A628A640DCADA87236FB2550EC8E3EA1DB96DCC3F803DB732A02D:1:AFEB33B99902(0.9516029745897732) BA{70:x_xxxxx_xxxxxxxxxxxxxxxx_x_x_xx_x_xxxxxxxxx_xxxxxxxxxxxxx_xxxxxx__xxxx} map[]}","ts":"2020-07-16T18:53:11.227766711Z"}
{"caller":"state.go:1788","level":"info","module":"tendermint:consensus","msg":"Added to lastPrecommits: VoteSet{H:412446 R:0 T:2 +2/3:AA28A527E07A628A640DCADA87236FB2550EC8E3EA1DB96DCC3F803DB732A02D:1:AFEB33B99902(0.954994140664999) BA{70:x_xxxxx_xxxxxxxxxxxxxxxx_x_x_xx_xxxxxxxxxxx_xxxxxxxxxxxxx_xxxxxx__xxxx} map[]}","ts":"2020-07-16T18:53:12.428217295Z"}
{"caller":"state.go:1788","level":"info","module":"tendermint:consensus","msg":"Added to lastPrecommits: VoteSet{H:412446 R:0 T:2 +2/3:AA28A527E07A628A640DCADA87236FB2550EC8E3EA1DB96DCC3F803DB732A02D:1:AFEB33B99902(0.9567678611133135) BA{70:x_xxxxx_xxxxxxxxxxxxxxxx_x_x_xx_xxxxxxxxxxx_xxxxxxxxxxxxx_xxxxxx_xxxxx} map[]}","ts":"2020-07-16T18:53:13.116591032Z"}
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x19499a4, 0x16)
        runtime/panic.go:1116 +0x72
runtime.sysMap(0xc0e4000000, 0x8000000, 0x2cdaad8)
        runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2cc3c60, 0x4800000, 0x2cc3c68, 0x2280)
        runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x2cc3c60, 0x2280, 0x0)
        runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x2cc3c60, 0x2280, 0x2570100, 0x2cdaae8, 0x2573540)
        runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x2cc3c60, 0x2280, 0x244620101, 0xc01bd70180)
        runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x4500000, 0xc029c30101, 0x479825)
        runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        runtime/malloc.go:1047 +0x46
runtime.systemstack(0x0)
        runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        runtime/proc.go:1041

goroutine 84 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xc029c3ef60 sp=0xc029c3ef58 pc=0x475980
runtime.mallocgc(0x4500000, 0x1651500, 0xa001, 0xc076ea7f80)
        runtime/malloc.go:1046 +0x895 fp=0xc029c3f000 sp=0xc029c3ef60 pc=0x41cdf5
runtime.makeslice(0x1651500, 0x4500000, 0x4500000, 0x316ab395)
        runtime/slice.go:49 +0x6c fp=0xc029c3f030 sp=0xc029c3f000 pc=0x45cb2c
github.com/dgraph-io/badger/v2/table.NewTableBuilder(0x4000000, 0x0, 0x2, 0x3f847ae147ae147b, 0x1000, 0x0, 0x1, 0xc00116ea80, 0x0, 0x1, ...)
        github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:99 +0x95 fp=0xc029c3f098 sp=0xc029c3f030 pc=0xec74d5
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables(0xc00011f180, 0x0, 0x1d3fae0, 0xc016bb3520, 0xc00116eba0, 0xc00116ec00, 0xc05ca1e840, 0x5, 0x5, 0xc05ca20440, ...)
        github.com/dgraph-io/badger/v2@v2.0.3/levels.go:535 +0x11a5 fp=0xc029c3f798 sp=0xc029c3f098 pc=0xef16b5
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef(0xc00011f180, 0x0, 0x1d3fae0, 0xc016bb3520, 0xc00116eba0, 0xc00116ec00, 0xc05ca1e840, 0x5, 0x5, 0xc05ca20440, ...)
        github.com/dgraph-io/badger/v2@v2.0.3/levels.go:837 +0xe1 fp=0xc029c3f9a0 sp=0xc029c3f798 pc=0xef3d51
github.com/dgraph-io/badger/v2.(*levelsController).doCompact(0xc00011f180, 0x0, 0x3ff0000000000000, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/dgraph-io/badger/v2@v2.0.3/levels.go:906 +0x49d fp=0xc029c3fe10 sp=0xc029c3f9a0 pc=0xef47bd
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc00011f180, 0xc00000efa0)`

It's looks like a OOM problem. but oasis-node still runing and signed.  I checked the our monitor system, and there was always an excess of memory on the host.

host config: 2c4G
