### ISSUE TITLE
go/common: Use `cbor.Versioned` more consistently through the codebase

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#3119]
While initially added as part of the new tx envelope format that (probably?) isn't getting merged, we should futureproof our descriptor formats further by using `cbor.Versioned` instead of having a `DescriptorVersion` field in each descriptor definition, as using the package will reduce code duplication when handling multiple versions (particularly as serialized data) is required.

Needs changes:
 * entity.Entity
 * registry/api.Runtime
 * node.Node

#3094 had the changes for this (since it was totally breaking anyway) but people changed their minds about supporting that feature (again), so it is unlikely to get merged.

~Note: This should be done the next time we have an excuse to break any of the data structures without requiring backward compatibility.~

**Comment by kostko** [comment]
Why would this be breaking, isn't the field name the same (`v`) and we already have versions in all the descriptors?

**Comment by Yawning** [comment]
Dealing with the old version and the new version is more cruft?

**Comment by kostko** [comment]
I don't think I understand, isn't the wire format exactly the same so the version number doesn't actually need to be changed?

**Comment by Yawning** [comment]
Why would it be the same?

```
type Entity struct { // nolint: maligned
        // DescriptorVersion is the entity descriptor version.
        //
        // It should be bumped whenever breaking changes are made to the descriptor.
        DescriptorVersion uint16 `json:"v,omitempty"`
```

I'm proposing to get rid of that field.

**Comment by kostko** [comment]
But you are suggesting to replace it with:
```
type Entity struct {
        cbor.Versioned
```

Where `cbor.Versioned` is:
```
type Versioned struct {
	V uint16 `json:"v"`
}
```

Shouldn't the wire format (CBOR) stay the same in this case? The field name and type are the same and embedding the struct makes the fields of the embedded struct available directly on the parent?

**Comment by Yawning** [comment]
Are we using a different definition of breaking?  I am using "All existing descriptors, are invalidated by my proposed change, therefore it is breaking".  If you are using something different, please let me know.

**Comment by kostko** [comment]
Why would the existing descriptors be invalidated if the wire format is the same?

**Comment by Yawning** [comment]
Existing descriptors have a field `DescriptorVersion uint16`.  After this change, the descriptor definition will have a field `cbor.Versioned`.  Under the English language I was taught in school, this is by definition, anything but "the wire format is the same".

**Comment by Yawning** [comment]
Oh I see.  Yeah ok nevermind.  We're using `v` as the existing struct tag.
