### ISSUE TITLE
Consider using go report

### ISSUE THREAD

**Issue by mitar** [oasisprotocol/oasis-core#3185]
##### SUMMARY

Go report is a handy service to help you run code quality on top of a repository. I think it would be useful to run it on this repository.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

CI

##### ADDITIONAL INFORMATION

See current report for this repository: https://goreportcard.com/report/github.com/oasisprotocol/oasis-core

It has quite a lot of spelling mistakes. :-)

**Comment by Yawning** [comment]
We run `golangci-lint` already.  The current config could be expanded on to add the checks that reported "problems", but some of them are rather annoying.

**Comment by Yawning** [comment]
#3188 is basically all I think we should do here.

**Comment by mitar** [comment]
Awesome!
