### ISSUE TITLE
Internal gRPC socket only initialized after consensus starts

### ISSUE THREAD

**Issue by joesixpack** [oasisprotocol/oasis-core#3303]
Under 20.10 Mainnet Dry Run while it is waiting for the Genesis start time (or not syncing), the internal.sock file is not available and thus the Oasis API server cannot read the status of the node messing up all apps dependent on the API server.

`ERROR: 2020/09/22 06:47:21 consensus_handler.go:205: Request at /api/pingnode failed to ping node :  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /home/j/serverdir/node/internal.sock: connect: no such file or directory"`

**Comment by kostko** [comment]
Thanks for the report, this should indeed be fixed.
