### ISSUE TITLE
Display and log a better error in case escrow transaction does not pass MinDelegationAmount

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3308]
Currently if an escrow transaction tries to delegate less than `MinDelegationAmount` the transaction fails with `staking.ErrInvalidArgument` and nothing is logged.

https://github.com/oasisprotocol/oasis-core/blob/6c6e70303b2cb18d72b6f4396ad8959fd2c3b5f4/go/consensus/tendermint/apps/staking/transactions.go#L178-L181

**Comment by kostko** [comment]
We could introduce a separate error for this, although this would be a consensus-breaking change.

**Comment by ptrus** [comment]
If we want to avoid a consensus-breaking change, then a good short-term improvement is just adding a log message.
