### ISSUE TITLE
P2P topic IDs should not include Minor/Patch versions of the RuntimeCommitteeProtocol

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3311]
P2P topic IDs include `RuntimeCommitteeProtocol` version: 
https://github.com/oasisprotocol/oasis-core/blob/61de25e20457fffd47df39bf7188096d036db5fb/go/worker/common/p2p/p2p.go#L233-L235

However since we are following SemVer, `Minor` and `Patch` version changes to the `RuntimeCommitteeProtocol` should be backwards compatible therefore also not resulting in a changed topic ID.

**Comment by ptrus** [comment]
The topics should probably also include chain IDs (or something similar to separate different network meshes).

**Comment by kostko** [comment]
Yeah so while the messages themselves use the chain domain separation context so they wouldn't be valid, we should probably separate the meshes to avoid needless messages.
