### ISSUE TITLE
Gossiped runtime transactions that fail initial checks are lost without the sender knowing

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3359]
After changing the runtime transaction dispatch mechanism to use gossipsub, the transactions can be lost without the sender (client) knowing about it or having a way to retry sending the same transaction.

Consider a runtime transaction that fails the initial transaction check by the runtime. Such a transaction will not be added to the transaction queue and will not be gossiped further. The problem is that the client will currently be unable to determine what happened with the problematic transaction as there is no way to propagate the error back to the client.

One possibility would be for the client to attempt to check the transaction locally before submitting it, but this would require the client node having access to the runtime in order to invoke transaction checks.

**Comment by ptrus** [comment]
Additionally, currently the client will retry all transactions indefinitely (on every epoch transition) so transactions that fail check-tx will keep getting retried, should probably fail request after some blocks/epochs, at least until client can do checktx?

**Comment by kostko** [comment]
Client nodes can now perform transaction checks locally if they have the runtime available.
