### ISSUE TITLE
Fix fuzz-build

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3374]
It seems that the `make -C go fuzz-build` target doesn't actually build in latest master, but for some reason CI is passing despite the build errors.

**Comment by kostko** [comment]
Seems to be caused by https://github.com/dvyukov/go-fuzz/issues/294 on Go 1.15.

**Comment by jberci** [comment]
The makefile changes are in #3373, but for the go-fuzz bug we'll need to wait. Until then, the pipeline step has a `soft_fail`.

**Comment by kostko** [comment]
It seems upstream has been fixed.
