### ISSUE TITLE
Runtime upgrade E2E test should wait for old node expiration

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3404]
Currently [the runtime upgrade E2E test](https://github.com/oasisprotocol/oasis-core/blob/e79b4979c20447f4b47ba4e7a35ae67e74647a0e/go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go) shuts down the old compute nodes after upgrade and starts the client, assuming that the new compute nodes will process the transactions:
https://github.com/oasisprotocol/oasis-core/blob/e79b4979c20447f4b47ba4e7a35ae67e74647a0e/go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go#L211-L220

The problem is that the committee scheduler can still schedule one of the old nodes, making the test flaky as it depends on what committee is elected. We should probably wait for the old nodes to expire before proceeding.

**Comment by Yawning** [comment]
This blocks #3180
