### ISSUE TITLE
Runtime client should retry checking blocks

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3412]
Runtime client should periodically re-check blocks in case checking block for transaction fails (e.g. due to a no storage node being available):

https://github.com/oasisprotocol/oasis-core/blob/1e3a6fe489f9077864cff8e4c779f2099b24db6e/go/runtime/client/watcher.go#L69-L73

Discovered in the daily e2e tests.

**Comment by kostko** [comment]
This is similar to #3388.
