### ISSUE TITLE
 Error in checking node status

### ISSUE THREAD

**Issue by chriswsq** [oasisprotocol/oasis-core#3465]
Excuse me, in the operation of oasis node control status - a UNIX / node / data of run a non validator node = = > checking node status/ internal.sock  When the command is executed, an error is reported: failed to query entities "error = RPC error: code = unavailable desc = connection error: desc = \ \" transport: error while dialing dial UNIX / serverdir / node/ internal.sock : connect: no such file or Directory, where is the problem?

**Comment by ptrus** [comment]
I think this means that the socket is not there (e.g. wrong path or node is not up). Can you post a full example?

**Comment by chriswsq** [comment]
Thank you, it has been solved, but I did not remove the parenthesis when Adding the address of the seed node
