### ISSUE TITLE
Storage node wont register if it cannot fetch runtime genesis block

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3483]
Currently storage node won't register if it cannot fetch roothash genesis state, which can be a bit problematic in the case when:
- runtime is suspended in genesis 
- and all nodes for the runtime register as storage+compute

In this scenario, there will be no roothash state until runtime is resumed. However the runtime will never be resumed as no node will register due to being unable to fetch the runtime genesis block, e.g:
```
{"caller":"node.go:716","err":"roothash: invalid runtime","level":"error","module":"worker/storage/committee","msg":"can't retrieve genesis block","runtime_id":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wE=","ts":"2020-11-05T07:50:55.677624116Z"}
```

Current known workaround is to register a compute-only node for the runtime so that runtime gets resumed.

**Comment by kostko** [comment]
This is probably resolved now that even suspended runtimes have state at genesis?

**Comment by ptrus** [comment]
Yeah i think that's right.
