### ISSUE TITLE
Allow more updates when registering an "expired" node

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3539]
Registering an expired (but not yet deleted) node is currently subject to the same update restriction rules as an active node being updated. However it would make sense for expired nodes to be allowed to update certain(most?) fields. 
AFAIK the reasons for restrictions apply mostly to active nodes - since most restrictions are there to prevent certain mid-epoch updates (e.g. removing node support for a runtime mid-epoch).

For example: currently a node needs to be unregistered for a debonding-period number of epochs, before it is able to register without a previously registered runtime.

**Comment by kostko** [comment]
> However it would make sense for expired nodes to be allowed to update certain(most?) fields.

As long as the consensus key cannot be updated for an expired node that's probably ok.
