### ISSUE TITLE
Support upgrades with different binary hashes

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3579]
Currently the upgrade module supports a single upgrade type ("internal") which relies on binary hash to ensure correct node version for upgrade is used:
https://github.com/oasisprotocol/oasis-core/blob/5af6d91815f01b7a2d195932c8c10fd9faa7e343/go/upgrade/api/api.go#L71-L73

We should stop using the hash of the binary to ensure correct version is running and instead use something like a software version. Otherwise upgrade will be hard to coordinate with people doing custom builds. 

Can either create a new upgrade type or update (and rename?) the existing `"internal"` upgrade type to not rely on exact matching binaries - as that doesn't seem all that useful.

Should do after https://github.com/oasisprotocol/oasis-core/pull/3536 is merged, as that PR contains some significant changes to the upgrade module.

Also enforce unique upgrade descriptor names.

**Comment by kostko** [comment]
> Can either update a new upgrade type or update (and rename?) the existing "internal" upgrade type to not rely on exact matching binaries - as that doesn't seem all that useful.

I would opt for reusing/renaming the existing upgrade type.
