### ISSUE TITLE
Add e2e test coverage for suspended runtimes in genesis

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-core#3619]
The code path in `InitChain()` in `go/consensus/tendermint/apps/registry/genesis.go` lacks test coverage for loading suspended runtimes from genesis state.

An e2e test should be added for this.

**Comment by kostko** [comment]
This is the same observation as #3484 which also mentions that tests should be added (in addition to fixing a bug with loading suspended runtimes from genesis state). I'm closing this in favor of the actual bug issue.

**Comment by ptrus** [comment]
Ah i did actually search for an issue before recommending to open one, but missed that one. Sorry for the unneeded work Andrej :grin:
