### ISSUE TITLE
Support new upstream SGX driver available in Linux kernels 5.11+

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#3651]
##### SUMMARY
It looks like the upcoming Linux kernel 5.11 will have support for Intel's SGX out of the box, i.e. no need for 3rd party kernel modules:
- https://lwn.net/Articles/840129/
- https://www.kernel.org/doc/html/latest/x86/sgx.html

Fortanix already added support for this new driver exposed via a device node at `/dev/sgx/enclave` (dubbed _Augusta_). However, there are still [some open issues](https://github.com/fortanix/rust-sgx/search?q=augusta&type=issues).

This requires updating the runtime loader to configure the new driver and the sandbox to properly expose the device node.

##### ISSUE TYPE
- Feature Idea

**Comment by gw0** [comment]
Ubuntu 21.04 is already packaging [linux-image-5.11.0-22-generic](https://packages.ubuntu.com/hirsute/linux-image-5.11.0-22-generic) that exposes the devices `/dev/sgx_enclave` and `/dev/sgx_provision`. When using Flexible Launch Control some udev rules need to be added to transition from the SGX DCAP driver `/dev/sgx/...` to the in-kernel SGX driver ([instructions](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/README.kernel.md)). For the Legacy Launch Control `/dev/isgx` (packaged by Fortanix and used by oasis-node) it seems something similar can be accomplished ([instructions](https://github.com/intel/linux-sgx/tree/master/docker/build#legacy-launch-control-driver-and-kernel-for-sgx)).

**Comment by kostko** [comment]
This seems to work out of the box using latest master.
