### ISSUE TITLE
beacon: Add more test cases

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#3665]
The beacon could use more test cases, as the ones that are present are fairly basic.

 * [ ] There probably should be test cases for the node being restarted mid-protocol round.

**Comment by kostko** [comment]
> There probably should be test cases for the node being restarted mid-protocol round.

The daily long-term tests may cover that as nodes are randomly killed there. But yeah probably something more deterministic should be done as well.

**Comment by kostko** [comment]
And it seems that the daily tests already found an issue related to restarts, see #3669.

**Comment by Yawning** [comment]
This particular beacon implementation, will be gone in the next major upgrade.
