### ISSUE TITLE
oasis-node debug fix-genesis CLI command doesn't configure beacon correctly

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#3728]
##### SUMMARY

The `oasis-node debug fix-genesis` CLI command doesn't configure beacon correctly:

Using the [2021-02-03 Testnet genesis file](https://github.com/oasisprotocol/testnet-artifacts/releases/download/2021-02-03/genesis.json), it fails with:

```
$ oasis-node debug fix-genesis -g genesis.json --genesis.new_file genesis-new.json
ts=2021-02-24T15:23:06.64897691Z level=error module=cmd/debug/fix-genesis caller=fixgenesis.go:191 msg="new genesis document sanity check failed" err="beacon: sanity check failed: unknown backend: ''"
```

The relevant part of the original `genesis.json`:

```json
  "beacon": {
    "params": {}
  },
```

The relevant part of the new `genesis-new.json`:

```json
  "beacon": {
    "base": 0,
    "params": {
      "backend": ""
    }
  },
```

##### ISSUE TYPE
- Bug Report

##### OASIS NODE VERSION

The latest `master` as of today: https://github.com/oasisprotocol/oasis-core/commit/c07c9877d7da5c17038193cd59dbde5bd8a096b6

```paste below
$ oasis-node --version
Software version: 20.12-gitc07c9877d
Consensus:
  Consensus protocol version: 3.0.0
Runtime:
  Host protocol version:      2.0.0
  Committee protocol version: 2.0.0
Go toolchain version: 1.15.6
```

**Comment by kostko** [comment]
Yeah we should probably change `fixgenesis` to fill in some default parameters that will be used for the mainnet upgrade.

**Comment by ptrus** [comment]
Also `Beacon.Base` should be transferred over from the original genesis.

Additionally `fixgenesis` should set some default governance parameters.

**Comment by ptrus** [comment]
`consensus.parameters.max_evidence_size` should also probably be filled by `fixgenesis` (computed from existing "max_evidence_num")
