### ISSUE TITLE
Couldn't connect to any seeds

### ISSUE THREAD

**Issue by wangke0809** [oasisprotocol/oasis-core#3898]
My node can't sync any blocks, and it logs Couldn't connect to any seeds.

Seed from docs: E27F6B7A350B4CC2B48A6CBE94B0A02B0DCB0BF3@35.199.49.168:26656

core version: 20.12.7

**Comment by ptrus** [comment]
Since the Cobalt upgrade you should be using `21.1.1` (https://docs.oasis.dev/general/oasis-network/network-parameters)

**Comment by wangke0809** [comment]
THX!
