### ISSUE TITLE
Replace grpcio with tonic

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/oasis-core#3992]
[grpcio](https://crates.io/crates/grpcio) has been swiftly overtaken by [tonic](https://crates.io/crates/tonic) and is hence better maintained. The porting effort shouldn't be too bad.

**Comment by nhynes** [comment]
doing this in the sdk repo instead.

**Comment by kostko** [comment]
Yeah grpcio stuff from this repository should probably be removed together with #3572.
