### ISSUE TITLE
Setup rust code linting

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#4170]
Setup [`clippy`](https://github.com/rust-lang/rust-clippy) in CI to lint rust code. 

Will probably require code fixes since the rust code currently won't pass all of the lints. To avoid some unnecessary work should do this only after:
- https://github.com/oasisprotocol/oasis-core/issues/3572

**Comment by Yawning** [comment]
We can also think about integrating more static analysis into our Rust (eg: https://github.com/rust-lang/miri).
