### ISSUE TITLE
Adjust log severity for consensus protocol events

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#4196]
Currently there are various log entries emitted from the consensus protocol under "warn" and "error" severities. The issue is that these entries may not refer to the local node so having such high severity may lead the node operator into a false belief that their node is at fault while the error actually occurred while processing an external transaction.

We should go over all the emitted log events and adjust the severity to be more appropriate.

**Comment by mitjat** [comment]
Discussed offline: First step is to demote all of these logs to `debug`, then maybe re-up their level if they originate from the current node.
