### ISSUE TITLE
Flaky go unit tests (consensus failure due to no registered validators)

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#4215]
oasis-node go unit tests sometime fail due to https://github.com/oasisprotocol/oasis-core/blob/346108c5675aab16ee391a13f87bc3d8dea4066c/go/consensus/tendermint/apps/governance/governance.go#L270-L272

What (i'm pretty sure) happens is:
- the loop in `MustAdvanceEpoch` increments epoch 3 times before the node registration worker is able to update its registration, causing no validators to be registered in registry
https://github.com/oasisprotocol/oasis-core/blob/346108c5675aab16ee391a13f87bc3d8dea4066c/go/beacon/tests/tester.go#L97-L116
- since `DebugStaticValidators` is used, the rest of the consensus is still making progress even if no validators are registered

Possible fix:
- ensure the test validator is registered for epoch+1, before tranversing to next epoch in `MustAdvanceEpoch` 
- also should remove the `DebugStaticValidators` option (and related debug code) as it's only used for unit tests, and fix any tests relying on it

**Comment by kostko** [comment]
I would be in favor of removing the `DebugStaticValidators` option.

**Comment by ptrus** [comment]
> I would be in favor of removing the DebugStaticValidators option.

Yeah i'l do that. But we also need the first one (wait in `MustAdvanceEpoch` enough time that node re-registers), as without `DebugStaticValidators` the consensus failure will happen on first epoch transition when there's no elected validator.
