### ISSUE TITLE
Bump Tendermint Core to 0.35

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#4249]
Tendermint Core 0.35-rc1 has been released. We should rebase our fork and make sure everything works. The release should be backwards compatible with 0.34.

**Comment by Yawning** [comment]
Our patches:
  * [ ] Revert "p2p: Fix "Unknown Channel" bug on CustomReactors (tendermint#…
  * [ ] replay: add debug option to skip corrupted messages in WAL replay
  * [ ] node: Flush pending incoming connections on EMFILE
  * [ ] libs/autofile: Don't panic on EMFILE
  * [ ] crypto/ed25519: Add support for oasis-core's domain separation
  * ~types: Use Ed25519 batch verification in VerifyCommit~ (Upstream does this, we helped)
  * ~crypto/ed25519: Use an optimized implementation~ (Upstream uses voi)

We will also need:
 * [ ] Change tendermint's Ed25519 verification semantics from ZIP-215 to the Oasis one (Easy, just define an Oasis flavor preset and use it, see our crypto/signature code).

**Comment by kostko** [comment]
> replay: add debug option to skip corrupted messages in WAL replay

I believe this one also shouldn't be needed anymore.

> Revert "p2p: Fix "Unknown Channel" bug on CustomReactors (tendermint#…

Upstream also fixed this in a new release after we reported it.

We may need to update things related to our lightweight seed node implementation due to some changes in the P2P stack. Maybe we can just use Tendermint's new "modes".

**Comment by kostko** [comment]
Tendermint v0.35 has just been released.

**Comment by Yawning** [comment]
I assume this is a WONTFIX at this point.
