### ISSUE TITLE
Possible memory leak on Cipher node

### ISSUE THREAD

**Issue by kernelpanic9** [oasisprotocol/oasis-core#4263]
Memory utilisation on Cipher node went up by 1.3Gb in 14 days (5.6G total). Please check for possible memory leak.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  36020 oasis     20   0  118.6g   5.4g   4.3g S  14.3  69.5   3479:30 oasis-node  
```

oasis-node is the main process on this machine.

![Screen Shot 2021-09-15 at 14 13 28](https://user-images.githubusercontent.com/14617216/133502846-58544ee2-dd1c-47f1-b75c-4fbbadf7d96c.png)

**Comment by kernelpanic9** [comment]
Memory util kept increasing with the rate of ~200MB/day.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                                  
  32360 oasis     20   0   67.4g   6.0g   1.0g S 281.1  79.4  10609:07 oasis-node          
```

I restarted the service. Mem util dropped by almost 50%.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                                  
 126741 oasis     20   0   56.3g   3.7g   3.0g R  15.3  48.2   1:51.36 oasis-node    
```

**Comment by kostko** [comment]
Thanks for your report. To help debug this, can you set `pprof.bind` in the node's configuration (e.g. to `127.0.0.1:3030`):
```yaml
pprof:
    bind: "127.0.0.1:3030"
```
Then can you fetch heap profiles by running:
```bash
wget -O heap-2021-09-18 http://127.0.0.1:3030/debug/pprof/heap
```

It would be good to get a few of these profiles from different points in time to see if there's anything obvious that stands out.

**Comment by kernelpanic9** [comment]
Ack, enabled. Will set up cron to take heap+top snapshots every day.

**Comment by kernelpanic9** [comment]
Memory util has increased by 1GB since service restart on Sep 18th. Attaching tar with daily heap snapshots.
[oasis-heap-09-19_09-27.tar.gz](https://github.com/oasisprotocol/oasis-core/files/7236326/oasis-heap-09-19_09-27.tar.gz)

**Comment by kostko** [comment]
Thanks for the snapshots, will take a look!

**Comment by kostko** [comment]
Based on the heap profiles we have identified one possible issue that should be fixed in #4290. Are you willing to test with the above fix applied to see if this resolves the issue? We can also provide an updated binary if needed.

**Comment by kernelpanic9** [comment]
Sure, I can test this. I can compile binaries when the fix is submitted.

**Comment by kostko** [comment]
Once #4291 is merged you can checkout the `stable/21.2.x` branch and build `oasis-node` from there to check if this fixes your issues.

**Comment by kostko** [comment]
The backported patch has been merged, can you re-test with a local build of the `stable/21.2.x` branch and report back? You should keep the heap snapshots enabled to help see if there are other related issues. Thanks!

**Comment by kernelpanic9** [comment]
Built and started. Will report back in ~7 days with results.

**Comment by kernelpanic9** [comment]
After ~5 hours running on custom binary I got constant 100% CPU utilisation, while mem util was normal. 
Attaching logs and heap during the issue.

![Screen Shot 2021-10-01 at 19 23 19](https://user-images.githubusercontent.com/14617216/135675191-724dd3de-b4a2-49c4-bad4-efcc700e5767.png)

[high_cpu_heap.tar.gz](https://github.com/oasisprotocol/oasis-core/files/7269653/high_cpu_heap.tar.gz)
[cipher_high_cpu_logs.tar.gz](https://github.com/oasisprotocol/oasis-core/files/7269654/cipher_high_cpu_logs.tar.gz)

After I restarted the service, CPU util went back to normal. 
Build was done from `stable/21.2.x` as requested:
`git clone -b stable/21.2.x  https://github.com/oasisprotocol/oasis-core`

**Comment by kernelpanic9** [comment]
Got 100% CPU again. Rolled back to pre-built 21.2.8. Any suggestions?


![Screen Shot 2021-10-02 at 11 05 07](https://user-images.githubusercontent.com/14617216/135725826-955007ac-250d-4f30-a241-88b3d8a5f874.png)

**Comment by kostko** [comment]
It seems that the patch has some unintended consequences as our daily long-term fuzzing tests have also been failing since the patch has been merged. Will look into it over the next week, please roll back for now.

**Comment by kostko** [comment]
Based on our quick tests it seems that #4292 fixes the above issue that is triggered by context cancellation not being properly handled. We will be releasing the fixes as part of 21.3.1 that is planned for later this week.

**Comment by kernelpanic9** [comment]
I can build and test the 21.3 branch when all fixes are backported.

**Comment by kostko** [comment]
Ok, so the fixes have already been backported to the `stable/21.3.x` branch. Thanks!

**Comment by kernelpanic9** [comment]
Build 21.3.x and started the node. Will keep you posted.

**Comment by kernelpanic9** [comment]
Looks like the memory leak got resolved. Attaching heap snapshots for confirmation.
[oasis-heap-2021-10-08.tar.gz](https://github.com/oasisprotocol/oasis-core/files/7310301/oasis-heap-2021-10-08.tar.gz)

**Comment by kostko** [comment]
That's great to hear, we'll be releasing 21.3.1 later today. Thanks for all the help in tracking this down!
