### ISSUE TITLE
oasis-test-runner/scenario/e2e/genesis_file makes it impossible to remove parameters

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#4374]
As part of my timekeeping/election changes from PVSS to VRF, I am deprecating and removing the PVSS backend.  The genesis document invariant checker in my branch correctly rejects genesis documents that attempt to configure the PVSS backend, because the backed no longer exists.

The e2e tests are written under the assumption that the mainnet document is well formed, but removing (and rejecting) parameters naturally breaks this assumption.  While I am probably going to end up disabling the test against the mainnet genesis document, this needs to be rethought and reconsidered, assuming that there is a good reason for this test to be there in the first place.

**Comment by kostko** [comment]
I ran into a similar problem in #4308 and modified the test so that it now instead runs fixgenesis on the Mainnet genesis file and verifies that the result is well-formed (e.g. passes sanity checks).

**Comment by Yawning** [comment]
> I ran into a similar problem in #4308 and modified the test so that it now instead runs fixgenesis on the Mainnet genesis file and verifies that the result is well-formed (e.g. passes sanity checks).

I am moderately unconvinced that this is sufficient.  I suppose that the new parameters could be hard-coded into the fixgenesis command, but that feels moderately bad for every single use-case of the command that isn't our mainnet/testnet.

**Comment by Yawning** [comment]
After some thought, just running fixgenesis for the test cases should be fine, since the test also happens to pull our current mainnet genesis document.
