### ISSUE TITLE
go/registry: Make submitting a VRF signing key mandatory

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#4394]
Once the network has transitioned to using VRF-driven elections, on the next major upgrade, mandate that node descriptors contain a valid VRF public key at genesis time.  Non-genesis registration tx-es currently already require a VRF public key.

**Comment by kostko** [comment]
You mean at genesis time, right? Because any registration transaction already must contain a VRF key.

**Comment by Yawning** [comment]
Yeah, I'll edit the issue to clarify this.
