### ISSUE TITLE
Switch to a unified runtime binary format

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#4469]
Instead of the mess we have in `go/runtime/registry/config.go`, we can make both our lives and that of our users much simpler by having a single binary, that is self-describing.

My proposal is to migrate to providing binaries as ZIP archives, with a manifest file that describes the relevant configuration parameters including:
 * Name
 * ID
 * Version
 * ELF executable file
 * SGX signature file (if relevant)
 * SGX executable file (if relevant)

To avoid confusion, while we will likely use the easy-to-work-with ZIP format, we should pick a new extension so that users are not tempted to extract the file.

While the manifest file is only going to ever be machine generated, and primarily machine parsed, it should be in a human readable format (`manifest.xml`, `manifest.json`, etc) to ease debugging, and the manifest file should be the only thing that has a fixed name in the archive.

**Comment by kostko** [comment]
> To avoid confusion, while we will likely use the easy-to-work-with ZIP format, we should pick a new extension so that users are not tempted to extract the file.

`.orc` (Oasis Runtime Container) :grin:

**Comment by Yawning** [comment]
Done in #4474
