### ISSUE TITLE
Adapt libp2p logger to our logging system

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#4531]
We should add an adapter for the libp2p logger so that all the logs are collected in one place.

**Comment by Yawning** [comment]
go/common/logging has this:
```
	// libp2p/IPFS uses yet another logging library, that appears to be a
	// wrapper around go-logging.  Because it's quality IPFS code, it's
	// configured via env vars, from the package `init()`.
	//
	// Till we can write a nice wrapper around it, to make it do what we
	// want, reach into the underlying library and squelch it.
	goLogging.Reset()
	_ = goLogging.SetBackend(goLogging.NewLogBackend(ioutil.Discard, "libp2p", goLog.LstdFlags))
```

But if we are getting logs, then they must have changed things when we weren't looking.

**Comment by ptrus** [comment]
Yes the ipfs logger is a wrapper around `zap` now, and it's somewhat configurable: https://github.com/ipfs/go-log/blob/604185d3545622df35d1bb76100bfc8b04293f9b/setup.go#L160-L162
