### ISSUE TITLE
Failed Vote TX

### ISSUE THREAD

**Issue by bitoven-dev** [oasisprotocol/oasis-core#4607]
##### SUMMARY

When I tried to submit vote tx, it gave an error:
```
level=error module=grpc/client caller=grpc.go:242 ts=2022-03-25T03:06:47.13475968Z msg="request failed" method=/oasis-core.Consensus/SubmitTx req_seq=1 rsp=null err="registry: no such node: governance: failed to query entity node: registry: no such node"
ts=2022-03-25T03:06:47.134838648Z level=error module=cmd/consensus caller=consensus.go:124 msg="failed to submit transaction" err="registry: no such node: governance: failed to query entity node: registry: no such node"
```
`**Laser Lemon**` from Slack said it was because I have one unregistered node listed on my entity.  After removed the unregistered node from my entity, my vote tx finally went through.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/oasisprotocol/oasis-core/blob/32eeab67e9f096c144b174201789edf73cf4dcf4/go/consensus/tendermint/apps/governance/transactions.go#L232

##### OASIS NODE VERSION

```paste
Software version: 21.3.10
Consensus:
  Consensus protocol version: 4.0.0
Runtime:
  Host protocol version:      4.0.0
  Committee protocol version: 3.0.0
Go toolchain version: 1.17.7
```

##### STEPS TO REPRODUCE

- Make a vote tx as guided in this link [https://docs.oasis.dev/general/run-a-node/upgrade-log/#2022-04-11-900-utc---damask-upgrade](https://docs.oasis.dev/general/run-a-node/upgrade-log/#2022-04-11-900-utc---damask-upgrade)
- When doing the last step (submit the generated transaction), it throw an error.

##### ACTUAL RESULTS

```paste below
level=error module=grpc/client caller=grpc.go:242 ts=2022-03-25T03:06:47.13475968Z msg="request failed" method=/oasis-core.Consensus/SubmitTx req_seq=1 rsp=null err="registry: no such node: governance: failed to query entity node: registry: no such node"
ts=2022-03-25T03:06:47.134838648Z level=error module=cmd/consensus caller=consensus.go:124 msg="failed to submit transaction" err="registry: no such node: governance: failed to query entity node: registry: no such node"
```

##### EXPECTED RESULTS

Transaction went through.

**Comment by tjanez** [comment]
> Would it be enough to change the order in entity.json file?

I think the best approach would be to re-register your entity with all non-working nodes being removed.

We're also working on documenting this. See https://github.com/oasisprotocol/docs/issues/56.
