### ISSUE TITLE
Logs on Testnet 22.0.2 contain non-ASCII characters

### ISSUE THREAD

**Issue by amela** [oasisprotocol/oasis-core#4621]
Logs on Testnet 22.0.2 contain non-ASCII characters:
```
{"caller":"basic_host.go:414","level":"debug","module":"libp2p:basichost","msg":"protocol
negotiation took 27.948<C2><B5>s","ts":"2022-03-23T09:38:44.015536269Z"}
```

**Comment by Yawning** [comment]
It's UTF-8 for `U+00B5` (lower case mu), because Go's default `time.Duration` string s11n routine  does that for micro seconds.

**Comment by Yawning** [comment]
Closing, this is working as intended (and yes, I would rather the Go developers used `u` instead).
