### ISSUE TITLE
Unable to Sync With the Testnet

### ISSUE THREAD

**Issue by blorgon1** [oasisprotocol/oasis-core#4680]
##### SUMMARY
When syncing a new node from scratch with the testnet, it panics with this message:
```
panic: Failed to process committed block (8535081:5864FDA0248A1FA53E65D36D9288EE89578003F8980D1900F76638737B43D0EE): wrong Block.Header.Version. Expected {11 25769803776}, got {11 21474836480}
```
Tried wiping state and retrying multiple times, same outcome each time.

##### ISSUE TYPE
- Bug Report

##### OASIS NODE VERSION
```
Software version: 22.1.3-git50ca03ad5
Consensus:
  Consensus protocol version: 6.0.0
Runtime:
  Host protocol version:      5.0.0
  Committee protocol version: 4.0.0
Go toolchain version: 1.17.7
```

##### OS / ENVIRONMENT
linux/amd64/docker

##### STEPS TO REPRODUCE
Following instructions from: https://docs.oasis.dev/general/run-a-node/set-up-your-node/run-non-validator
Using genesis file and seed nodes from: https://docs.oasis.dev/general/foundation/testnet/

##### ACTUAL RESULTS
```
level=info caller=replay.go:278 ts=2022-04-21T19:35:10.590884744Z module=tendermint:consensus msg="Completed ABCI Handshake - Tendermint and App are synced" appHeight=0 appHash=
level=info module=tendermint:base caller=node.go:333 ts=2022-04-21T19:35:10.59100559Z msg="Version info" tendermint_version=0.34.15 block=11 p2p=8
level=info caller=node.go:352 ts=2022-04-21T19:35:10.591099123Z module=tendermint:consensus msg="This node is not a validator" addr=515B77B3D5817CBD86FA80FABC907710D5770AF0 pubKey="unsupported value type"
...
level=info caller=pex_reactor.go:533 ts=2022-04-21T19:35:10.605604851Z module=tendermint:pex msg="No addresses to dial. Falling back to seeds"
level=info caller=switch.go:715 ts=2022-04-21T19:35:10.605620695Z module=tendermint:p2p msg="Dialing peer" address=05eac99bb37f6daad4b13386ff5e087acbddc450@34.86.165.6:26656
...
panic: Failed to process committed block (8535081:5864FDA0248A1FA53E65D36D9288EE89578003F8980D1900F76638737B43D0EE): wrong Block.Header.Version. Expected {11 25769803776}, got {11 21474836480}

goroutine 289 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00846c1c0, 0x0)
        github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:110 +0x85
```

##### EXPECTED RESULTS
The node should sync with the testnet.

**Comment by ouohh** [comment]
I have the same problem

**Comment by kostko** [comment]
The current instance of the Testnet has gone through a protocol upgrade. So you must start with Oasis Core 22.0.3 and when the node stops for upgrade switch to 22.1.3.

We will be updating our documentation to take this into account.

**Comment by blorgon1** [comment]
Okay thanks!

Are there any testnet state snapshots that could be downloaded instead?

**Comment by tjanez** [comment]
> The current instance of the Testnet has gone through a protocol upgrade. So you must start with Oasis Core 22.0.3 and when the node stops for upgrade switch to 22.1.3.
> 
> We will be updating our documentation to take this into account.

The Oasis Docs were updated in https://github.com/oasisprotocol/docs/pull/96/files#diff-0705f85e49787dde772a9a414305d70e14365603f5d3b5d1e8a9ddcf6d083047.

Also, since the [2023-10-12 Testnet Upgrade](https://docs.oasis.io/node/testnet/upgrade-log#2023-10-12-upgrade), this is no longer an issue.
