### ISSUE TITLE
Query For Block/Transaction By Hash

### ISSUE THREAD

**Issue by blorgon1** [oasisprotocol/oasis-core#4708]
##### SUMMARY
It would be useful to have grpc endpoints for querying blocks and transactions by their hash.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
go/consensus

##### ADDITIONAL INFORMATION
I don't see any method to uniquely query transactions from the consensus layer, transactions are only retrievable by the height of the block they're contained in. It would also be helpful to have an endpoint to query blocks by their hash as well.

**Comment by Yawning** [comment]
Both of those queries requires an indexer which is out of scope for oasis-core.

**Comment by blorgon1** [comment]
@Yawning what indexer is recommended for use?

**Comment by Yawning** [comment]
Oasisscan does.  It is also extremely easy to write something that maintains the mappings required.

It is not information that oasis-node requires to function, and it is a non-trivial amount of additional state to maintain, which is why it is out of scope for this project.
