### ISSUE TITLE
Configurable location of the gRPC socket (internal.sock)

### ISSUE THREAD

**Issue by gw0** [oasisprotocol/oasis-core#4850]
##### SUMMARY

For *oasis-node* the location of the gRPC UNIX socket (`internal.sock`) needs to be configurable in order to work with other non-root services. I suggest we add an optional configuration option, such as `socket:` into `config.yml`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`go/oasis-node/cmd/common`

##### ADDITIONAL INFORMATION

The *oasis-node* service needs to communicate with other services in order to be useful. We are likely encouraging bad practices, because the gRPC UNIX socket is located at `{{datadir}}/internal.sock` and we are enforcing strict permissions `chmod 700 {{datadir}}`. On Debian-like systems services typically open UNIX sockets under `/run` to expose it to other services (e.g. `/run/cups/cups.sock`) ("Modern Linux distributions include a /run directory as a temporary filesystem (tmpfs) which stores volatile runtime data.").

Exposing the non-authenticated gRPC socket should not be considered dangerous, especially if you expose it to a trusted other service. And even if you expose it over the network, the most an attacker can do is cause DoS (shutdown), he still can not do perform actually dangerous things, like manipulate the local state, trigger double-signing, steal any funds...

Alternatives considered:

- other service needs to run in Docker on Linux and have `internal.sock` mounted in: **good practice**, but requires Docker daemon to run as root
- other service needs to run as `root` or as the same user as *oasis-node*: **dangerous practice**, because the other service has access to all oasis-node files which defeats the purpose of `chmod 700` (other service can has full control, can manipulate local state, cause double signing...)
- have a post-start script that waits for *oasis-node* to perform the startup permission-check and then changes them `chgrp sharedgroup {{datadir}} {{datadir}}/internal.sock && chmod 710 {{datadir}} && chmod 770 {{datadir}}/internal.sock`: **bad practice**, ugly workaround
- if we transition towards local abstract namespace sockets independent from filesystem `\0oasis-node.socket`: **bad practice**, because we throw away filesystem permissions that can limit access to the gRPC socket (every process on the system has full control)
- if we transition towards loopback TCP sockets: *bad practice*, because everything depends on correctly set firewall rules that only give access to the other service (if firewall is incorrectly set, every process or even everyone on the local network has full control)
- we could also implement https://github.com/oasisprotocol/oasis-core/issues/3994 and make the other gRPC UNIX socket configurable: **good practice**, but requires the decision what is "less safe" and what not

Options that do not work:

- it does not work if you set special ACL permissions (`setfacl`) to the other service, because these also get reflected in permissions the startup permission-check still fails
- other service can not run in Docker on Mac/Windows, because you can not mount `internal.sock` inside from outside Docker

**Comment by Yawning** [comment]
https://github.com/oasisprotocol/oasis-core/blob/master/go/oasis-node/cmd/common/grpc/grpc.go#L34
