### ISSUE TITLE
Apply `OASIS_UNSAFE_SKIP_KM_POLICY` in KM client

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/oasis-core#4876]
##### SUMMARY

It's useful to have a debug ORC of a confidential paratime that runs anywhere using any KM. `OASIS_UNSAFE_SKIP_KM_POLICY` signals "I don't care about KM policies" to the KM itself, but [not the client](https://github.com/oasisprotocol/oasis-core/blob/c9fe2a5684f586d73ced378559c5c168caf83cd0/keymanager-client/src/client.rs#L88-L95). This env var could usefully be applied in both places to allow debug ORCs.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

keymanager-client

**Comment by Yawning** [comment]
While I have no problems with this idea in theory, what safeguards beyond "Dont' do that then" do you propose to prevent the debug enclave from being accidentally deployed?

**Comment by kostko** [comment]
Agree that switching this on by accident is a problem. I guess the same could be said for the existing uses of `OASIS_UNSAFE_SKIP_KM_POLICY`. Any suggestions?

We could only allow this in either non-SGX builds (still can be dangerous though as you also want non-SGX clients to authenticate the EnclaveRPC channel to the key manager) or when allowing debug enclaves is enabled through `OASIS_UNSAFE_ALLOW_DEBUG_ENCLAVES` (as this requires use of unsafe flags all over the place).

**Comment by Yawning** [comment]
Probably only for debug enclaves?

**Comment by nhynes** [comment]
It's hard to link anything in the code itself to the enclave being in debug mode, as that's assigned only after the application is compiled. I think an easy thing to do would be to expose the debug-ness in the `core.RuntimeInfo` query and have the runtime host compare that to its own debug-ness.

**Comment by kostko** [comment]
> only after the application is compiled

The thing with our runtimes is that they can be in either debug mode in which case they only accept debug quotes or in non-debug mode in case they only accept non-debug quotes. This depends on the build-time `OASIS_UNSAFE_ALLOW_DEBUG_ENCLAVES` flag and is also reflected in `oasis_core_runtime::BUILD_INFO.is_secure`. The runtime will also not process any requests in case the attestation is invalid (including checking the debug-ness of itself).

Reporting the `is_secure` status in addition to this mechanism (as is done for the key manager runtime) as part of the runtime connection handshake would probably be useful for the node to report a better error message.

If we require `OASIS_UNSAFE_ALLOW_DEBUG_ENCLAVES` to be set in order for `OASIS_UNSAFE_SKIP_KM_POLICY` to take effect that would prevent one accidentally building a non-debug runtime which skips policy checks.

**Comment by kostko** [comment]
This is now implemented in #4878, please take a look.
