### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by iamif3000** [oasisprotocol/oasis-core#5091]
I use oasis-core/go as a mod and see a compiling error.
```
 /go/pkg/mod/github.com/oasisprotocol/oasis-core/go@v0.2202.3/consensus/tendermint/crypto/signature.go:64:7: undefined: ed25519.EnableOasisDomainSeparation
```
I checked the code, there's no "EnableOasisDomainSeparation".

**Comment by Yawning** [comment]
Upstream tendermint doesn't have it.

https://github.com/oasisprotocol/oasis-core/blob/master/go/go.mod#L14
https://github.com/oasisprotocol/tendermint/blob/v0.34.15-oasis/crypto/ed25519/oasis_core.go#L50

**Comment by iamif3000** [comment]
> Upstream tendermint doesn't have it.
> 
> https://github.com/oasisprotocol/oasis-core/blob/master/go/go.mod#L14 https://github.com/oasisprotocol/tendermint/blob/v0.34.15-oasis/crypto/ed25519/oasis_core.go#L50

But you do have it here 
https://github.com/oasisprotocol/oasis-core/blob/master/go/consensus/tendermint/crypto/signature.go
```
func init() {
	tmed.EnableOasisDomainSeparation(string(tendermintSignatureContext))
}
```

**Comment by iamif3000** [comment]
> > Upstream tendermint doesn't have it.
> > https://github.com/oasisprotocol/oasis-core/blob/master/go/go.mod#L14 https://github.com/oasisprotocol/tendermint/blob/v0.34.15-oasis/crypto/ed25519/oasis_core.go#L50
> 
> But you do have it here https://github.com/oasisprotocol/oasis-core/blob/master/go/consensus/tendermint/crypto/signature.go
> 
> ```
> func init() {
> 	tmed.EnableOasisDomainSeparation(string(tendermintSignatureContext))
> }
> ```

ignore this reply.. I misunderstood you.

**Comment by kostko** [comment]
Yes, @Yawning implied that you need to use a `replace` directive in your `go.mod` in order to point to [our fork of Tendermint Core](https://github.com/oasisprotocol/tendermint).
