### ISSUE TITLE
setting a coefficient can fail

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#5829]
https://github.com/oasisprotocol/oasis-core/blob/18da8bc49d92a543795246b8bb7fb574df070eec/secret-sharing/src/poly/univariate.rs#L72

as the doc string says, if the coefficient doesn't exist, this is a no-op.  i think this should return a bool -- not necessarily require that the results be used via `Result` or `must_use` attribute -- so that the caller can do something about it.

the current way for those who care is to check the degree via `size` before setting the coefficient, which essentially does a double check on the success path.  possibly the compiler can optimize it away, but it's not obvious and if the API can be both caller friendly and compiler friendly, why not?

**Comment by peternose** [comment]
> i think this should return a bool

Agree. Will fix for univariate and bivariate case.
