### ISSUE TITLE
should check for potential usize overflow

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#5833]
https://github.com/oasisprotocol/oasis-core/blob/18da8bc49d92a543795246b8bb7fb574df070eec/secret-sharing/src/poly/bivariate.rs#L34

deg_x and deg_y are usize and deg_x + 1 and deg_y + 1 can overflow to zero.  better to panic here rather than later.

**Comment by bennetyee** [comment]
u8 input parameters will never cause usize to panic

**Comment by peternose** [comment]
To avoid this problem and to avoid using degrees as they break constant time operations, I think I should just get rid of degrees and always work with sizes. This will simplify everything.
