### ISSUE TITLE
some coefficients should be non-zero

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#5857]
https://github.com/oasisprotocol/oasis-core/blob/b0e6bc88be7a3fe051ea1d35b06e8d33691d5aec/secret-sharing/src/poly/bivariate.rs#L50

the precondition is that b(x,y) should be such the shares b(1,0), b(2,0), ..., b(m,0), b(m+1,0), ..., etc should be shares of a polynomial that has degree m, so f(x) = b(x,0) has degree m and g(y) = b(0,y) has degree n (swapped m,n etc here?).  so the coefficients b_{i,j} has precondition b_{m,0} \ne 0 and b_{0,n} \ne 0.

this is, of course, extremely unlikely, but it might be good to avoid those anyway?  of course, this applies to randomization w/ zero-holed bivariate polynomials too -- those coefficients must not cancel out the corresponding coefficients in the old/original bivariate polynomial.

it may be okay to just leave this as a comment, since the likelihood of it occurring is extremely low, and the impact is that it takes one fewer share to reconstruct.   the reconstruction code, however, could get into trouble if too few shares are needed, so could lead to assertion failures or other kinds of failures if this were to occur.  i think i'd prefer explicitly avoiding it by generate-and-test, even if it's not constant time and reveals info about the RNG state.

**Comment by peternose** [comment]
> i think i'd prefer explicitly avoiding it by generate-and-test

Agree. Will change to that.

> even if it's not constant time

It is not constant time, but it doesn't reveal any sensitive data except that one output of the RNG was "zero".

> reveals info about the RNG state.

It reveals the output of RNG and not its internal state, so this should not be a security concern.

**Comment by peternose** [comment]
>  those coefficients must not cancel out the corresponding coefficients in the old/original bivariate polynomial

I will add an extra verification after participant receives and combines bivariate shares (dealing phase) or combines proactive bivariate shares and randomizes the existing share (handoff). Since bivariate polynomial is not know to participants, this verification of the newly created share verifies the corresponding elements of the verification matrix.
