### ISSUE TITLE
Releases of Development / testing images should be automated

### ISSUE THREAD

**Issue by willscott** [oasisprotocol/oasis-core#971]
by having them manually pushed to dockerhub by developers, we risk getting bad images pushed. we should have a CI process to rebuild, update versions, and release

**Comment by kostko** [comment]
The images should also be tagged with the proper release versions, e.g. `20.3` for the `20.3.x` branch and `master` or `latest` for the master branch. CI should use the corresponding tag (master should use master and stable branches should use the stable tag).

This would avoid the need to backport irrelevant changes when toolchain versions are bumped in master.

**Comment by kostko** [comment]
This was done in #2970.
